permissions:
  contents: write

name: Build and Publish

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install build dependencies
      run: |
        uv pip install build bump-my-version
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Get merged branch name
      id: merged-branch
      run: |
        if [[ ${{ github.event_name }} == 'push' ]]; then
          # For direct pushes to dev, use the current branch name
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
        else
          # For pull requests, get the source branch name
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        fi
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
    
    - name: Determine version bump type
      id: version-bump
      run: |
        if [[ ${{ steps.merged-branch.outputs.branch_name }} =~ ^(feat|feature)/ ]]; then
          echo "bump_type=minor" >> $GITHUB_OUTPUT
        elif [[ ${{ steps.merged-branch.outputs.branch_name }} =~ ^(fix|bugfix)/ ]]; then
          echo "bump_type=patch" >> $GITHUB_OUTPUT
        else
          echo "bump_type=dev" >> $GITHUB_OUTPUT
        fi
    
    - name: Bump version
      run: |
        if [[ ${{ steps.version-bump.outputs.bump_type }} == "dev" ]]; then
          bump-my-version bump dev
        else
          bump-my-version bump ${{ steps.version-bump.outputs.bump_type }}
        fi
        git push
        git push --tags

  build-and-publish:
    needs: bump-version
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for bump-my-version to work with tags
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install build dependencies
      run: |
        uv pip install build bump-my-version
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Bump version on master
      if: github.ref == 'refs/heads/master'
      run: |
        bump-my-version bump release
        git push
        git push --tags
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      env:
        UV_PUBLISH_USERNAME: __token__
        UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv pip publish dist/*