permissions:
  contents: write

name: Build and Publish

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install build dependencies
      run: |
        uv pip install build bump-my-version --system
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Get merged branch name
      if: github.ref == 'refs/heads/dev'
      id: merged-branch
      run: |
        if [[ ${{ github.event_name }} == 'push' ]]; then
          # For direct pushes to dev, use the current branch name
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
        else
          # For pull requests, get the source branch name
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        fi
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
    
    - name: Check current version
      if: github.ref == 'refs/heads/dev'
      id: current-version
      run: |
        CURRENT_VERSION=$(grep 'current_version = ' pyproject.toml | cut -d'"' -f2)
        echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
    
    - name: Determine version bump type
      if: github.ref == 'refs/heads/dev'
      id: version-bump
      run: |
        CURRENT_VERSION=${{ steps.current-version.outputs.version }}
        if [[ $CURRENT_VERSION =~ -dev[0-9]+$ ]]; then
          echo "bump_type=dev" >> $GITHUB_OUTPUT
        elif [[ ${{ steps.merged-branch.outputs.branch_name }} =~ ^(feat|feature)/ ]]; then
          echo "bump_type=minor" >> $GITHUB_OUTPUT
        else
          echo "bump_type=patch" >> $GITHUB_OUTPUT
        fi
    
    - name: Bump version on dev
      if: github.ref == 'refs/heads/dev'
      run: |
        bump-my-version bump ${{ steps.version-bump.outputs.bump_type }}
        git push
        git push --tags
    
    - name: Bump version on master
      if: github.ref == 'refs/heads/master'
      run: |
        bump-my-version bump release
        git push
        git push --tags
    
    - name: Build package
      run: uv build
    
    - name: Publish to PyPI
      env:
        UV_PUBLISH_USERNAME: __token__
        UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv publish